### ISSUE TITLE
Running vagrant up error

### ISSUE THREAD

**Issue by kelomina** [saferwall/saferwall#457] opened 2023-12-29 01:16 UTC
Windows cmd：
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3aa5d7e5-a779-4704-aab7-495f1de9df20", "--type", "headless"]

Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file /dev/null (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by LordNoteworthy** [comment] 2024-09-14 01:02
Duplicate of https://github.com/saferwall/saferwall/issues/444

**Closed by LordNoteworthy** 2024-09-14 01:02 UTC
